// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG5U3y1LIwzYfI-bLaL8qk5-aa6OAZSE8',
    appId: '1:1082846160023:web:7e5b3e710105eab21cb5d2',
    messagingSenderId: '1082846160023',
    projectId: 'advanced-chatapp-edee7',
    authDomain: 'advanced-chatapp-edee7.firebaseapp.com',
    storageBucket: 'advanced-chatapp-edee7.firebasestorage.app',
    measurementId: 'G-DW4V1WTY2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPT2Mf8l0cA-vw2r1wHSVZASslEtI9iI0',
    appId: '1:1082846160023:android:a0123d02f9ec95781cb5d2',
    messagingSenderId: '1082846160023',
    projectId: 'advanced-chatapp-edee7',
    storageBucket: 'advanced-chatapp-edee7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1By2ENdmrzAeaSap7tshjesbzWr5VKns',
    appId: '1:1082846160023:ios:14fce23d03355bf61cb5d2',
    messagingSenderId: '1082846160023',
    projectId: 'advanced-chatapp-edee7',
    storageBucket: 'advanced-chatapp-edee7.firebasestorage.app',
    iosBundleId: 'com.example.wabusiness.socialmedia',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1By2ENdmrzAeaSap7tshjesbzWr5VKns',
    appId: '1:1082846160023:ios:14fce23d03355bf61cb5d2',
    messagingSenderId: '1082846160023',
    projectId: 'advanced-chatapp-edee7',
    storageBucket: 'advanced-chatapp-edee7.firebasestorage.app',
    iosBundleId: 'com.example.wabusiness.socialmedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe1YcPXOmxyu6uVZ1ISQSdfwT2XjxkcmE',
    appId: '1:1082846160023:web:d6fcc123b8ae673c1cb5d2',
    messagingSenderId: '1082846160023',
    projectId: 'advanced-chatapp-edee7',
    authDomain: 'advanced-chatapp-edee7.firebaseapp.com',
    storageBucket: 'advanced-chatapp-edee7.firebasestorage.app',
    measurementId: 'G-51SE6GK62X',
  );

}